Turned deployment into a usable bash script.
It is now possible to create a set of servers automatically using the deployment script. It is very rough and ready with almost no error handling!

diff --git a/deployment b/deployment
--- a/deployment
+++ b/deployment
@@ -1,28 +1,72 @@
-# Looks like a bash script, but not yet ready for the prime-time! There is no error handling
-# and so on, so it would not be a good idea to run this as a script.
-#
-# This file essentially serves as a deployment how-to for the moment.
-# To deploy alfresco in docker, execute the lines below one at a time as required.
+#!/bin/bash
+
+scriptname=`basename $0`
+
+function show_usage
+{
+    echo "Usage: $scriptname [options] command" >&2
+    echo "Where options are:" >&2
+    echo "  -p        Prefix for server names, e.g. -p 42 will create Alfresco servers 42-alf1 42-alf2 etc." >&2
+    echo "  -n        Number of Alfresco servers, e.g. -n 2 to create a cluster of two servers." >&2
+    echo "Valid commands are:" >&2
+    echo "  create    Create the specified containers."
+}
+
+while getopts p:n:h option; do
+    case $option in
+        p)
+            prefix=$OPTARG
+            ;;
+        n)
+            num_alf_servers=$OPTARG
+            ;;
+        h)
+            show_usage
+            exit 1
+            ;;
+    esac
+done
+
+shift $((OPTIND-1))
+
+if [[ "$1" == "" ]]; then
+    echo "Missing command, see '$scriptname -h' for details." >&2
+    exit 1
+fi
+
+command=$1
+
+if [[ "$command" != "create" ]]; then
+    echo "Invalid command '$command', see '$scriptname -h' for details." >&2
+    exit 1
+fi
+
+if [[ "$prefix" != "" ]]; then
+    prefix="${prefix}-"
+fi
+
+if [[ "$num_alf_servers" == "" ]]; then
+    num_alf_servers=1
+fi
 
 # Create a data volume container
 # This is used for the content store shared across all repository instances.
-docker run -d --name alfdata -v /alfresco/data ubuntu:14.04 echo 'Alf 4.2 data container'
-
+data_container_name=${prefix}alfdata
+docker run -d --name $data_container_name -v /alfresco/data ubuntu:14.04 echo 'Alfresco data container'
+echo "Created common data container: $data_container_name"
 
 # Create a database server
 # The database 'alfresco' may be accessed by the repositories using username 'postgres'
 # and password '' (empty/none)
-docker run -d -P --name alfdb mattward/alfpostgres
+db_server_name=${prefix}alfdb
+docker run -d -P --name $db_server_name mattward/alfpostgres
+echo "Created database server $db_server_name"
 
+alfresco_image="mattward/alfresco:4.2"
 
-
-# Create an alfresco server, mapping the tomcat HTTP connector to 8080
-# If using boot2docker, use 'boot2docker ip' to find the VM's IP address, then it is possible
-# to access http://<ip>:8080/alfresco and http://<ip>:8080/share from the real host (e.g. your Mac).
-docker run -d --hostname docker-host-a --name alfa --link alfdb:alfdb --volumes-from alfdata -p 8080:8080 mattward/alfresco:4.2
-
-# Create a second alfresco instance, add more in the same way but be sure
-# to give them individual host names and map 8080 to a unique port. This one will
-# map the tomcat connector to 8081 on the real host.
-docker run -d --hostname docker-host-b --name alfb --link alfdb:alfdb --volumes-from alfdata -p 8081:8080 mattward/alfresco:4.2
-
+for (( i = 0; i < $num_alf_servers; i++ )); do
+    server_name=${prefix}alf$((i+1))
+    external_port=$((i+8081))
+    docker run -d --hostname ${server_name} --name ${server_name} --link $db_server_name:alfdb --volumes-from $data_container_name -p ${external_port}:8080 ${alfresco_image}
+    echo "${server_name} mapped to port ${external_port}"
+done
